[package]
name = "img-fuse"
version = "0.1.0"
authors = ["Caio O Campos <caio.campos1204@gmail.com.br>"]
edition = "2018"

[dependencies]
glob = "0.3.0"
rand = "0.7.2"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
image = "0.22.3"
resvg = { version = "0.8.0", features = ["cairo-backend"] }
handlebars = "2.0.2"
